{{- /*
SPDX-License-Identifier: MIT
SPDX-FileCopyrightText: 2026 FreeCAD
SPDX-FileNotice: Part of the Trigo theme for Hugo.
*/ -}}

{{- /* CMS config:

- Get CMS params from config/params.yaml.
- Merge some site config defaults.
- Output CMS config setup to be used by CMS Admin page.
*/ -}}


{{- if site.Params.enable_cms -}}

{{- $repo := site.Params.git_repository -}}
{{- $url := urls.Parse $repo -}}

site_url: {{ site.BaseURL }}

app_title: {{ site.Params.cms_app_title | default "Admin CMS" }}
logout_redirect_url: {{ site.Params.cms_logout_redirect_url }}
logo:
  src: {{ site.Params.cms_logo_src }}

backend:
  name: {{ index (split ($url.Hostname) ".") 0 }}
  repo: {{ strings.TrimSuffix ".git" (trim $url.Path "/") }}
  branch: {{ site.Params.cms_branch | default "main" }}
  auth_methods: [token]

{{/*
# publish_mode: editorial_workflow # NOTE: not supported yet, see
# https://sveltiacms.app/en/docs/workflows/editorial
*/ -}}

media_folder: /static
public_folder: /
asset_collections:
  - name: sponsors
    label: Sponsors
    icon: person_add
    media_folder: /assets/sponsors
    public_folder: /sponsors
  - name: icons
    label: Icons
    icon: add_reaction
    media_folder: /themes/trigo/assets/svg
    public_folder: /svg
media_libraries:
  default:
    config:
      max_file_size: 1024000 # in bytes
      slugify_filename: true
      transformations:
        raster_image: # original format
          format: webp # new format, only `webp` is supported with sveltia for now
          quality: 80
          width: 1600
          height: 1600
        svg:
          optimize: true

i18n:
  structure: multiple_folders
  locales: [en, zh, es, fr, pt, de, ja]
  default_locale: en
  initial_locales: default

slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"
  trim: true
  lowercase: true

output:
  omit_empty_optional_fields: true

field_defaults:
  richtext:
    linked_images: false

collections:

  - name: homepage
    label: Homepage
    media_folder: ""
    public_folder: ""
    thumbnail: cover.image
    icon: home
    i18n: true
    files:
      - name: homepage
        label: Homepage
        file: "{{ "content/{{locale}}/_index.md" }}"
        icon: home
        i18n: true
        fields:
          - name: title
            label: Title
            widget: string
            i18n: true
          - name: description
            label: Description
            widget: string
            i18n: true
          - name: linkTitle
            label: Link Title
            widget: string
            i18n: true
            required: false
          - name: cover
            label: Cover
            widget: object
            i18n: true
            required: false
            fields:
              - { name: image, label: Image, widget: image, i18n: duplicate, required: false }
              - { name: caption, label: Caption, widget: string, i18n: true, required: false }
          - name: body
            label: Body
            widget: richtext
            i18n: true
            required: false

{{- range where hugo.Sites.Default.Sections "Section" "!=" "admin" }}

  - divider: true

  {{ if not .Pages -}}

  - name: {{ .Section }}-section
    label: {{ humanize .Section }}
    description: {{ humanize .Section }} section
    media_folder: ""
    public_folder: ""
    thumbnail: cover.image
    icon: {{ .Page.Params.icon_cms }}
    i18n: true
    files:
      - name: {{ .Section }}-section-index
        label: {{ humanize .Section }}
        file: {{ printf "content/{{locale}}/%s/_index.md" .Section }}
        icon: {{ .Page.Params.icon_cms }}
        i18n: true
        fields:
          - name: title
            label: Title
            widget: string
            i18n: true
          - name: description
            label: Description
            widget: string
            i18n: true
          - name: linkTitle
            label: Link Title
            widget: string
            i18n: true
            required: false
          - name: cover
            label: Cover
            widget: object
            i18n: true
            required: false
            fields:
              - { name: image, label: Image, widget: image, i18n: duplicate, required: false }
              - { name: caption, label: Caption, widget: string, i18n: true, required: false }
          - name: body
            label: Body
            widget: richtext
            i18n: true
            required: false

  {{- else -}}

  - name: {{ .Section }}-pages
    label: {{ humanize .Section }}
    description: {{ humanize .Section }} collection
    folder: content
    path: '
    {{- if eq .Section (index site.MainSections 0) -}}
      {{- printf "%s/{{year}}/{{month}}/{{slug}}/index" .Section -}}
    {{- else if eq .Section "download" -}}
      {{- printf "%s/releases/{{slug}}/index" .Section -}}
    {{- else if .Sections -}}
      {{- printf "%s/{{slug}}/_index" .Section -}}
    {{- else -}}
      {{- printf "%s/_index" .Section -}}
    {{- end -}}'
    media_folder: ""
    public_folder: ""
    thumbnail: cover.image
    icon: {{ .Page.Params.icon_cms }}
    summary: "{{ "**{{title}}** {{date | date('DD MMM YYYY')}} {{draft | ternary('(draft)', '')}} · {{authors | default('no authors')}} · {{locales | upper}}" }}"
    reorder:
      key: weight
    i18n: true

    sortable_fields:
      fields: [title, date, authors]
      default:
        field: date
        direction: descending

    view_groups:
      groups:
        - name: year
          label: Year
          field: date
          pattern: '\d{4}'
        - name: category
          label: Categories
          field: categories
      default: year

    view_filters:
      filters:
        - name: drafts
          label: Drafts
          field: draft
          pattern: true
        - name: posts_2023
          label: Posted in 2023
          field: date
          pattern: '^2023'
        - name: posts_2024
          label: Posted in 2024
          field: date
          pattern: '^2024'
        - name: posts_2025
          label: Posted in 2025
          field: date
          pattern: '^2025'
        - name: posts_2026
          label: Posted in 2026
          field: date
          pattern: '^2026'
        {{ if eq .Section (index site.MainSections 0) -}}
        - name: announcement
          label: Announcement
          field: categories
          pattern: announcement
        - name: event
          label: Event
          field: categories
          pattern: event
        - name: feature
          label: Feature
          field: categories
          pattern: feature
        - name: showcase
          label: Showcase
          field: categories
          pattern: showcase
        - name: tutorial
          label: Tutorial
          field: categories
          pattern: tutorial
        - name: update
          label: Update
          field: categories
          pattern: Update
        {{- end }}

    index_file:
      label: {{ humanize .Section }} Index
      icon: home
      i18n: true
      fields:
        - name: title
          label: Title
          widget: string
          i18n: true
        - name: description
          label: Description
          widget: string
          i18n: true
        - name: linkTitle
          label: Link Title
          widget: string
          i18n: true
          required: false
        - name: redirect
          label: Redirect
          widget: string
          i18n: duplicate
          required: false
        - name: cover
          label: Cover
          widget: object
          i18n: true
          required: false
          fields:
            - { name: image, label: Image, widget: image, i18n: duplicate, required: false }
            - { name: caption, label: Caption, widget: string, i18n: true, required: false }
        - name: body
          label: Body
          widget: richtext
          i18n: true
          required: false

    fields:
      - name: title
        label: Title
        widget: string
        i18n: true
      - name: description
        label: Description
        widget: string
        i18n: true
        required: false
      {{ if .Sections -}}
      - name: linkTitle
        label: Link Title
        widget: string
        i18n: true
        required: false
      - name: redirect
        label: Redirect
        widget: string
        i18n: duplicate
        required: false
      {{ end -}}
      - name: date
        label: Date
        widget: datetime
        i18n: duplicate
      - name: draft
        label: Draft
        widget: boolean
        default: false
        i18n: duplicate
        required: false
      {{ if eq .Section (index site.MainSections 0) -}}
      - name: authors
        label: Authors
        widget: string
        i18n: duplicate
        required: false
      - name: categories
        label: Categories
        widget: select
        options:
          - { label: Announcement, value: announcement }
          - { label: Event, value: event }
          - { label: Feature, value: feature }
          - { label: Showcase, value: showcase }
          - { label: Tutorial, value: tutorial }
          - { label: Update, value: update }
        i18n: duplicate
        required: false
      - name: tags
        label: Tags
        widget: list
        i18n: duplicate
        required: false
      {{ end -}}
      - name: cover
        label: Cover
        widget: object
        i18n: true
        required: false
        fields:
          - { name: image, label: Image, widget: image, i18n: duplicate, required: false }
          - { name: caption, label: Caption, widget: string, i18n: true, required: false }
      - name: body
        label: Body
        widget: richtext
        i18n: true

  {{- end -}}

{{- end }}

  - divider: true

  - name: theme
    label: Theme i18n
    icon: language
    i18n: true
    files:
      - name: translations
        label: Theme Translations
        file: "{{ "themes/trigo/i18n/{{locale}}.yaml" }}"
        icon: language
        i18n: true
        fields:
          - name: strings
            label: i18n strings
            widget: list
            root: true
            summary: "{{ "{{id}} - {{translation}}" }}"
            i18n: true
            allow_add: false
            allow_remove: false
            allow_duplicate: false
            allow_reorder: false
            hint: "{{ "Template variables such as {{ .Count }} are supported." }}"
            fields:
              - name: id
                label: Translation ID
                widget: string
                i18n: duplicate
              - name: translation
                label: Translation
                widget: string
                i18n: true

singletons:

  - name: settings
    label: Site Settings
    file: config/_default/params.yaml
    icon: settings
    fields:
      - name: site_authors
        label: Default site authors
        widget: string
      - name: site_keywords
        label: Site keywords and tags
        widget: list
      - name: site_logo
        label: Site logo
        widget: image
        media_folder: /static
        public_folder: /
      - name: default_icon
        label: Default placeholder icon
        widget: image
        media_folder: /static
        public_folder: /
      - name: git_repository
        label: Git repository URL
        widget: string
      - name: socials
        label: Social media links
        widget: list
        summary: "{{ "{{label}}" }}"
        collapsed: auto
        fields:
          - name: label
            label: Label
            widget: string
          - name: url
            label: Social media URL
            widget: string
      - name: style
        label: Theme Style
        hint: Only change the value. Please leave the key (variable name) as-is.
        widget: keyvalue
        key_label: CSS variable name
        value_label: CSS value

  - divider: true

  - name: sponsors
    label: Sponsors list
    file: data/sponsors.yaml
    icon: person_add
    fields:
      - name: sponsors
        label: Sponsors
        label_singular: Sponsor
        widget: list
        summary: "{{ "{{label}} - {{tier}}" }}"
        thumbnail: logo
        collapsed: auto
        root: true
        fields:
          - name: id
            label: Sponsor ID
            widget: hidden
            default: "{{ "{{uuid_shorter}}" }}"
          - name: label
            label: Label
            widget: string
          - name: description
            label: Description
            widget: string
            required: false
          - name: logo
            label: Logo
            widget: image
            media_folder: /assets/sponsors
            public_folder: /sponsors
            required: false
          - name: link
            label: Link
            widget: string
            required: false
          - name: tier
            label: Sponsoring tier
            widget: select
            options:
              - { label: Corporate, value: corporate }
              - { label: Gold, value: gold }
              - { label: Early, value: early }
              - { label: Silver, value: silver }
              - { label: Bronze, value: bronze }
          - name: start_date
            label: Start date
            widget: datetime
            type: date

{{- end -}}