# General Hugo default config.
# For custom Params Theme-related and CMS see params.yaml.

baseURL: https://www.freecad.org/
title: FreeCAD

defaultContentLanguage: en

theme: trigo

menus:
  main:
  - pageRef: /features
  - pageRef: /download
  - pageRef: /news
  - pageRef: /community
  - pageRef: /docs
    identifier: docs
  - pageRef: /manual
    parent: docs
  - pageRef: /dev
    parent: docs
  - pageRef: /api
    parent: docs
  - pageRef: /donate
    params:
      class:
        - button
        - donate

  footer:
  - pageRef: /
  - pageRef: /features
  - pageRef: /download
  - pageRef: /news
    identifier: news
  - pageRef: /news/archives
    parent: news
  - pageRef: /community
  - pageRef: /docs
    identifier: docs
  - pageRef: /manual
    parent: docs
  - pageRef: /dev
    parent: docs
  - pageRef: /api
    parent: docs
  - pageRef: /donate

taxonomies:
  category: categories
  tag: tags
  author: authors

mainSections:
  - news
  - manual
  - dev

summaryLength: 20

# Max number of listed pages (splits).
pagination:
  pagerSize: 12

buildDrafts: false
buildFuture: false
buildExpired: false

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
enableGitInfo: true


# Override url scheme (e.g. omit news section sub-folders).
permalinks:
  page:
    news: /:sections[0]/:slugorcontentbasename

cascade:
  - weight: 1
    target:
      kind: home
      path: "{/}"

  - weight: 20
    target:
      kind: section
      path: "{/features}"

  - weight: 30
    target:
      kind: section
      path: "{/download}"

  - weight: 40
    target:
      kind: section
      path: "{/news}"

  - weight: 50
    target:
      kind: section
      path: "{/community}"

  - weight: 60
    target:
      kind: section
      path: "{/docs}"

  - weight: 70
    target:
      kind: section
      path: "{/manual}"

  - weight: 80
    target:
      kind: section
      path: "{/dev}"

  - weight: 90
    target:
      kind: section
      path: "{/api}"

  - weight: 100
    target:
      kind: section
      path: "{/donate}"

  - weight: 110
    target:
      kind: section
      path: "{/admin}"

  - params:
      partials:
        content:
          - download
    target:
      kind: page
      path: /download/releases/**

  - params:
      partials:
        hero:
          - download
    target:
      kind: section
      path: /download/unstable

  - params:
      partials:
        content:
          - sponsors
    target:
      path: /donate

  - params:
      toc: true
    target:
      path: /dev/**

outputs:
  home:
    - html
    - cms_config
    - rss
  section:
    - html
  taxonomy:
    - html
  term:
    - html

outputFormats:
  cms_config:
    baseName: cms-config
    mediaType: application/yaml
    isHTML: false
    isPlainText: true
    notAlternative: true

# Keep for local dev. Production build uses --minify.
minify:
  minifyOutput: false

services:
  googleAnalytics:
    id: # Google Analytics G-MEASUREMENT_ID.

frontmatter:
  lastmod:
  - lastmod
  - modified
  - :git
  - date
  - publishdate
  - pubdate
  - published

markup:
  goldmark:
    duplicateResourceFiles: false
    parser:
      attribute:
        block: true
        title: true
      autoDefinitionTermID: true
      wrapStandAloneImageWithinParagraph: false
    renderer:
      unsafe: true
    extensions:
      strikethrough: false
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
  highlight:
    style: dracula # NOTE: Currently overridden by highlight.css. Keep for now.
    lineNos: false
    noClasses: false
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false

imaging:
  quality: 75
  resampleFilter: mitchellNetravali
  exif:
    disableDate: true
    disableLatLong: true

privacy:
  googleAnalytics:
    disable: true
    respectDoNotTrack: true
  youtube:
    disabled: false
    privacyEnhanced: true

caches:
  getresource:
    dir: :cacheDir/:project
    maxAge: 24h
  modules:
    dir: :cacheDir/modules
    maxAge: 24h
  images:
    dir: :cacheDir/images