# Languages default config (development environment)

en:
  contentDir: content/en
  disabled: false
  label: English
  locale: en-US
  direction: ltr
  weight: 1
  params:
    site_description: Your own free and open-source parametric modeler
    locale_flag: 🇬🇧

zh:
  contentDir: content/zh
  disabled: false
  label: 中文
  locale: zh-CN
  direction: ltr
  weight: 2
  params:
    site_description: 你自己的自由开源参数化建模器
    locale_flag: 🇨🇳

es:
  contentDir: content/es
  disabled: false
  label: Español
  locale: es-ES
  direction: ltr
  weight: 3
  params:
    site_description: Tu propio modelador paramétrico libre y de código abierto
    locale_flag: 🇪🇸

fr:
  contentDir: content/fr
  disabled: false
  label: Français
  locale: fr-FR
  direction: ltr
  weight: 4
  params:
    site_description: Votre modeleur paramétrique libre et open-source
    locale_flag: 🇫🇷

pt:
  contentDir: content/pt
  disabled: false
  label: Português brasileiro
  locale: pt-BR
  direction: ltr
  weight: 5
  params:
    site_description: Seu próprio modelador paramétrico livre e de código aberto
    locale_flag: 🇧🇷

de:
  contentDir: content/de
  disabled: false
  label: Deutsch
  locale: de-DE
  direction: ltr
  weight: 6
  params:
    site_description: Dein eigener freier und Open-Source parametrischer Modellierer
    locale_flag: 🇩🇪

ja:
  contentDir: content/ja
  disabled: false
  label: 日本語
  locale: ja-JP
  direction: ltr
  weight: 7
  params:
    site_description: あなた自身の自由でオープンソースのパラメトリックモデラー
    locale_flag: 🇯🇵

ru:
  contentDir: content/ru
  disabled: false
  label: Русский
  locale: ru-RU
  direction: ltr
  weight: 8
  params:
    site_description: Ваша собственная бесплатная программа параметрического моделирования с открытым исходным кодом
    locale_flag: 🇷🇺

tr:
  contentDir: content/tr
  disabled: false
  label: Türkçe
  locale: tr-TR
  direction: ltr
  weight: 9
  params:
    site_description: Kendi ücretsiz ve açık kaynaklı parametrik modelleyiciniz
    locale_flag: 🇹🇷

it:
  contentDir: content/it
  disabled: false
  label: Italiano
  locale: it-IT
  direction: ltr
  weight: 10
  params:
    site_description: Il tuo modellatore parametrico libero e open-source
    locale_flag: 🇮🇹

pl:
  contentDir: content/pl
  disabled: false
  label: Polski
  locale: pl-PL
  direction: ltr
  weight: 11
  params:
    site_description: Twój własny program do parametrycznego modelowania wolne i otwarte
    locale_flag: 🇵🇱

nl:
  contentDir: content/nl
  disabled: false
  label: Nederlands
  locale: nl-NL
  direction: ltr
  weight: 12
  params:
    site_description: Jouw eigen parametrische vrije en opensource tekenprogramma
    locale_flag: 🇳🇱

ar:
  contentDir: content/ar
  disabled: false
  label: عربي
  locale: ar
  direction: rtl
  weight: 13
  params:
    site_description: أداة النمذجة البارامترية المجانية والمفتوحة المصدر الخاصة بك
    locale_flag: 🇸🇦
