name: Bug report
description: Report a problem to help improve the website project.
title: "Bug: "
labels: Bug
type: bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please [search](https://github.com/freecad/Website/issues) if a similar reported bug already exists.
        This bug report template helps ensure issues can be reviewed and solved efficiently.
        Please do not add 2 unrelated issues in a single report.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Clear and concise description of the problem and how it impacts user experience, workflow or performance.
      placeholder: Describe the problem briefly.
    validations:
      required: true

  - type: dropdown
    id: dir
    attributes:
      label: Page collection affected
      options:
        - Homepage
        - Features
        - Download
        - News
        - Community
        - Documentation
        - Donate
        - Others
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a recipe to help reliably reproduce the issue.
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to ...
        2. Click on ...
    validations:
      required: true

  - type: textarea
    id: system
    attributes:
      label: System affected
      description: Provide basic info on the system affected by the issue.
      placeholder: |
        - Device: e.g. Desktop, Tablet, Smartphone
        - Viewport size: e.g. 1920x1080px, 360x800px
        - Operating system: e.g. Android 16, iOS 26
        - Browser: e.g. Chrome 145.0, Firefox 147.0
        - Hugo Version: e.g. 0.160.0 if applicable
    validations:
      required: true