# Languages production config (production environment)

en:
  disabled: false

zh:
  disabled: false

es:
  disabled: false

fr:
  disabled: false

pt:
  disabled: false

de:
  disabled: false

ja:
  disabled: false

ru:
  disabled: true

tr:
  disabled: true

it:
  disabled: true

pl:
  disabled: true

nl:
  disabled: true

ar:
  disabled: true